#! /bin/sh

if [[ -f $HOME/.bash_profile ]]; then
    mv $HOME/.bash_profile $HOME/.bash_profile.local
fi

ln -s $(bin/getconfigpath)/.bash_profile $HOME/.bash_profile

if [[ -f $HOME/.vimrc ]]; then
    mv $HOME/.vimrc $HOME/.vimrc.local
fi

ln -s $(bin/getconfigpath)/.vimrc $HOME/.vimrc
