#! /bin/sh

function isNotAlreadyLinked() {
    local IS_NOT_LINKED=1

    if [[ ! -h $HOME/$1 || $(readlink $HOME/$1) != $(bin/getconfigpath)/$1 ]]; then
	IS_NOT_LINKED=0
    fi
 
    return $IS_NOT_LINKED
}

# Link .bash_profile

if [[ -f $HOME/.bash_profile ]]; then
	if isNotAlreadyLinked .bash_profile; then
            mv $HOME/.bash_profile $HOME/.bash_profile.local
        fi
fi

if type dircolors > /dev/null 2>&1; then
    ln -s .dircolors $HOME
fi

ln -s .bash_profile $HOME

# Link .vimrc

if [[ -f $HOME/.vimrc ]]; then
    if isNotAlreadyLinked .vimrc; then
        mv $HOME/.vimrc $HOME/.vimrc.local
    fi
fi

ln -s .vimrc $HOME

